#!/bin/bash

`rm ./js/compiled.js`
scripts=("/js/util.js" "/js/dao/Dao.js" "/js/game/OnlineGamePlay.js" "/js/dom/Element.js" "/js/dom/ElementBuilder.js" "/js/constants.js" "/js/card/CardImage.js" "/js/card/Card.js" "/js/card/PlayingCard.js" "/js/card/PictureCard.js" "/js/card/CardImageBuilder.js" "/js/deck/Deck.js" "/js/deck/PlayingCardDeck.js" "/js/deck/PictureCardDeck.js" "/js/game/GameBoard.js" "/js/game/GameBoardBuilder.js" "/js/game/Player.js" "/js/game/Game.js" "/js/control/GameConfigController.js" "/js/view/GameConfigView.js" "/js/view/GameConfigViewBuilder.js" "/js/game/ScoreBoard.js")

for s in ${scripts[@]}; do
    echo $s
    `cat .$s >> ./js/compiled.js`
done
